version: '3.3'
services:
  server:
    image: todo/server:latest
    restart: always
    environment:
      DATABASE_URL: 'jdbc:mysql://db:3306/todo'
      DATABASE_USER: 'admin'
      DATABASE_PASS: 'root'
      SERVER_PORT: 2020
      spring.profiles.active: 'local-docker'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '2202:2020'
    expose:
      # Opens port 3306 on the container
      - '2202'
      # Where our data will be persisted
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
