apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.name }}-secret
  namespace: {{ .Values.global.namespace }}
data:
  {{- range $k, $v := .Values.secret }}
    {{ $k }}: {{ $v | b64enc }}
  {{- end }}
