name: CD Server
on:
  push:
    branches:
      - main
jobs:
  build:
    name: CD development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build the Docker image
        run: docker build --build-arg JAR_FILE=./build/libs/todo-0.0.1-SNAPSHOT.jar -t todo/server .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_DOCKER_HUB_TOKEN }}

      - name: Login to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600
      
      - name: TAG Docker image
        run: docker tag todo/server registry.digitalocean.com/kia-repo/todo-server

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/kia-repo/todo-server

  helm-lint:
    name: Helm lint and release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Helm Lint
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./helm-chart
      - name: Helm install
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade todo ./.chart -n todo
          kubeconfig: '${{ secrets.KUBECONFIG }}'


# Kia-Laptop:todo kiarsy$ helm --kube-context digitalocean upgrade todo ./.chart/ -n todo


      # - name: Helm Upgrade
      #   uses: 'deliverybot/helm@v1'
      #   with:
      #     release: 'todo'
      #     namespace: 'todo'
      #     chart: './.chart/'
      #     # token: '${{ github.token }}'
      #   env:
      #     KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'